#define noerror	   0
#define	dsterrstr  1
#define	sterrstr   2
#define	regerrstr  3
#define	noregstr   4
#define	flagerrstr 5
#define	sizerrstr  6
#define	unrecopstr 7
#define	brakerrstr 8
#define	basregerr  9
#define	autoerrstr 10
#define	inderrstr  11
#define	experrstr  12
#define	decerrstr  13
#define	hexerrstr  14
#define	binerrstr  15
#define	chrerrstr  16
#define	memerrstr  17
#define	enderrstr  18
#define	bgnerrstr  19
#define	symerrstr  20
#define	deferrstr  21
#define	laberrstr  22
#define	byterrstr  23
#define	miserrstr  24
#define	dfserrstr  25
#define	outerrstr  26
#define	enterrstr  27
#define	intrerrstr 28
#define	inclerrstr 29
#define	defmerrstr 30
#define	nparerrstr 31
#define	paraerrstr 32
#define	invmodestr 33
#define badstrerr  34
#define txtenderr  35
#define endmerrstr 36
#define parsuperr  37
#define mismoderr  38
#define pasdeferr  39
#define nameptherr 40
#define noblkerr   41
#define exeadderr  42

extern char *errtext [];
