char	*errtext [] =
	{
	"",
	"Destination register missing",
	"Can't push/pull stack pointer",
	"Bad register name",
	"No register names found",
	"Bad flag name",
	"Register size missmatch",
	"Unknown instruction",
	"No closing indirection bracket",
	"Bad base register name",
	"Can't use offset with auto inc/dec mode",
	"Can't indirect off bytesize inc/dec",
	"Bad expression",
	"Invalid decimal digit",
	"Invalid hexadecimal digit",
	"Invalid binary digit",
	"Bad character constant",
	"Out of memory",
	"Unexpected END",
	"Too many BEGIN's",
	"Undefined Symbol",
	"Symbol already defined",
	"Missing label",
	"Value out of byte range",
	"Missing expression",
	"Can't use forward reference in defs/ds or redef expression",
	"Write failure on output file",
	"ENTRY is invalid at outer level",
	"Assembly interrupted",
	"File name missing",
	"Can't nest macro definitions",
	"Too many parameters",
	"Bad parameter name",
	"Invalid addressing mode",
	"Bad string",
	"Text ended while in nested block",
	"Can't label ENDM",
	"Missing parameter",
	"Missing addressing mode",
	"Symbol undefined on previous pass!",
	"Incomplete name path",
	"Invalid block name",
	"Exec address already set"
	};
