extern char skipspace ();
extern char *next_field ();
extern char *strend ();
extern char *strip_quotes ();
extern bool check_name ();
extern char *bound_str ();
extern char *strupper ();
extern char *strdup ();
extern int safecmp ();
